on: 
  push:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Choco Package
        uses: crazy-max/ghaction-chocolatey@v2
        with:
          args: pack
      - name: Choco Push
        uses: crazy-max/ghaction-chocolatey@v2
        with: 
          args: push --source "'https://push.chocolatey.org/'"  --api-key ${{ secrets.CHOCO_API_KEY }} 